CLASS zcl_gw_openapi_test_mpc_ext DEFINITION
  PUBLIC
  INHERITING FROM zcl_zgw_openapi_test_mpc
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_GW_OPENAPI_TEST_MPC_EXT IMPLEMENTATION.
ENDCLASS.
